<?php

/**
 * @file
 * Generates markup to be displayed. FUnctionality in this Controller is wired to a route in my.routing.yml
 */

 namespace Drupal\my\Controller;

 use Drupal\Core\Controller\ControllerBase;

 class FirstController extends ControllerBase {

    public function simpleContent() {
        return [
            '#type' => 'markup',
            '#markup' => t("<h3>Hello World!</h3> <br>
            This is a simple page generated by my module inside a controller in college project's custom module."),
        ];
    }
    public function variableContent($name_1, $name_2) {
        return [
            '#type' => 'markup',
            '#markup' => t("The names are $name_1 and $name_2."),
        ];
    }
 }
