<?php

namespace Drupal\my\Controller;

use Drupal\Core\Controller\ControllerBase;

/**
 * Provides route responses for the My module.
 */
class FirstController extends ControllerBase {

  /**
   * Returns simple content.
   *
   * @return array
   *   A render array containing the markup.
   */
  public function simpleContent() {
    return [
      '#type' => 'markup',
      '#markup' => $this->t('<h3>Hello World!</h3><br>
      This is a simple page generated by my module inside a controller in the college project\'s custom module.'),
    ];
  }

  /**
   * Returns content with variables.
   *
   * @param string $name_1
   *   The first name.
   * @param string $name_2
   *   The second name.
   *
   * @return array
   *   A render array containing the names.
   */
  public function variableContent($name_1, $name_2) {
    return [
      '#type' => 'markup',
      '#markup' => $this->t('The names are @name1 and @name2.', [
        '@name1' => $name_1,
        '@name2' => $name_2,
      ]),
    ];
  }

}
