<?php

/**
 * @file
 * Demonstrates how to use hook functions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function my_cron() {
  \Drupal::messenger()->addMessage(t('Hellowwwwwwwwwwwww'));
  \Drupal::logger('my')->notice('Hellowwwwwwwwwwwww');
}

/**
 * Implements hook_form_alter().
 *
 * The form is passed by reference so that it can be altered.
 */
function my_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  \Drupal::messenger()->addMessage(t('Form ID for this form is @form_id.', ['@form_id' => $form_id]));

  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t('Save this article');
  }

  if ($form_id == 'node_article_form') {
    $form['actions']['submit']['#value'] = t('Create article');
  }
}
