<?php

/**
 * @file
 * Primary module hooks for vaibhav_entity_api module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function vaibhav_entity_api_theme(): array {
  // Calls the custom_profile.html.twig template file.
  return [
    'custom_profile' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for custom profile templates.
 *
 * Default template: custom-profile.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the custom profile
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_custom_profile(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function vaibhav_entity_api_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish custom profiles.
      $storage = \Drupal::entityTypeManager()->getStorage('custom_profile');
      $custom_profile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($custom_profile_ids) as $custom_profile) {
        $custom_profile->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize custom profiles.
      $storage = \Drupal::entityTypeManager()->getStorage('custom_profile');
      $custom_profile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($custom_profile_ids) as $custom_profile) {
        $custom_profile->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function vaibhav_entity_api_user_predelete(UserInterface $account): void {
  // Delete custom profiles that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('custom_profile');
  $custom_profile_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($custom_profile_ids)
  );
  // Delete old revisions.
  $custom_profile_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($custom_profile_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
